export const seedData = {
  locations: [
    { name: 'Pantry' },
    { name: 'Fridge' },
    { name: 'Freezer' },
  ],
  ingredient_categories: [
    {
      name: 'Protein & Eggs',
      icon: '🥩',
      color: '#ef4444',
      description: 'Meat, seafood, eggs, legumes, and other protein-rich ingredients.',
    },
    {
      name: 'Dairy',
      icon: '🥛',
      color: '#38bdf8',
      description: 'Milk, cream, cheese, yogurt, cultured dairy, and butter.',
    },
    {
      name: 'Grains & Bakery',
      icon: '🌾',
      color: '#f59e0b',
      description: 'Grains, pasta, bread, baked goods, and baking ingredients.',
    },
    {
      name: 'Oils, Nuts & Seeds',
      icon: '🫒',
      color: '#22c55e',
      description: 'Cooking oils, nuts, seeds, nut butters, and other shelf-stable fats.',
    },
    {
      name: 'Produce',
      icon: '🥬',
      color: '#10b981',
      description: 'Fresh fruits, vegetables, leafy greens, herbs, and aromatics.',
    },
    {
      name: 'Herbs, Spices & Seasonings',
      icon: '🧂',
      color: '#8b5cf6',
      description: 'Spices, herbs, seasonings, and flavor enhancers for culinary prep.',
    },
    {
      name: 'Condiments & Sauces',
      icon: '🍶',
      color: '#06b6d4',
      description: 'Sauces, dressings, vinegars, dips, and table condiments.',
    },
    {
      name: 'Beverages',
      icon: '☕',
      color: '#64748b',
      description: 'Hot and cold beverages, juices, coffees, teas, and liquid refreshments.',
    },
    {
      name: 'Snacks & Prepared Foods',
      icon: '📦',
      color: '#94a3b8',
      description: 'Snacks, sweets, frozen foods, and ready-to-eat or instant meals.',
    },
  ],
  get nutrient_types() {
    return this.ingredient_categories;
  },
  categories: [
    // Produce
    { name: 'Fruits', ingredient_category: 'Produce', nutrient_type: 'Produce' },
    {
      name: 'Vegetables',
      ingredient_category: 'Produce',
      nutrient_type: 'Produce',
    },
    {
      name: 'Herbs & Greens',
      ingredient_category: 'Produce',
      nutrient_type: 'Produce',
    },
    { name: 'Aromatics', ingredient_category: 'Produce', nutrient_type: 'Produce' },

    // Protein & Eggs
    { name: 'Meat', ingredient_category: 'Protein & Eggs', nutrient_type: 'Protein & Eggs' },
    { name: 'Seafood', ingredient_category: 'Protein & Eggs', nutrient_type: 'Protein & Eggs' },
    { name: 'Eggs', ingredient_category: 'Protein & Eggs', nutrient_type: 'Protein & Eggs' },
    {
      name: 'Beans & Legumes',
      ingredient_category: 'Protein & Eggs',
      nutrient_type: 'Protein & Eggs',
    },
    {
      name: 'Tofu & Tempeh',
      ingredient_category: 'Protein & Eggs',
      nutrient_type: 'Protein & Eggs',
    },

    // Dairy
    { name: 'Milk & Cream', ingredient_category: 'Dairy', nutrient_type: 'Dairy' },
    { name: 'Cheese', ingredient_category: 'Dairy', nutrient_type: 'Dairy' },
    {
      name: 'Yogurt & Cultured Dairy',
      ingredient_category: 'Dairy',
      nutrient_type: 'Dairy',
    },
    { name: 'Butter', ingredient_category: 'Dairy', nutrient_type: 'Dairy' },

    // Grains & Bakery
    { name: 'Grains', ingredient_category: 'Grains & Bakery', nutrient_type: 'Grains & Bakery' },
    { name: 'Pasta', ingredient_category: 'Grains & Bakery', nutrient_type: 'Grains & Bakery' },
    {
      name: 'Bread & Bakery',
      ingredient_category: 'Grains & Bakery',
      nutrient_type: 'Grains & Bakery',
    },
    {
      name: 'Baking Ingredients',
      ingredient_category: 'Grains & Bakery',
      nutrient_type: 'Grains & Bakery',
    },

    // Oils, Nuts & Seeds
    {
      name: 'Oils',
      ingredient_category: 'Oils, Nuts & Seeds',
      nutrient_type: 'Oils, Nuts & Seeds',
    },
    {
      name: 'Nuts & Seeds',
      ingredient_category: 'Oils, Nuts & Seeds',
      nutrient_type: 'Oils, Nuts & Seeds',
    },
    {
      name: 'Nut Butters',
      ingredient_category: 'Oils, Nuts & Seeds',
      nutrient_type: 'Oils, Nuts & Seeds',
    },

    // Herbs, Spices & Seasonings
    {
      name: 'Seasoning Blends',
      ingredient_category: 'Herbs, Spices & Seasonings',
      nutrient_type: 'Herbs, Spices & Seasonings',
    },
    {
      name: 'Spices & Dried Herbs',
      ingredient_category: 'Herbs, Spices & Seasonings',
      nutrient_type: 'Herbs, Spices & Seasonings',
    },

    // Condiments & Sauces
    {
      name: 'Condiments',
      ingredient_category: 'Condiments & Sauces',
      nutrient_type: 'Condiments & Sauces',
    },
    {
      name: 'Sauces',
      ingredient_category: 'Condiments & Sauces',
      nutrient_type: 'Condiments & Sauces',
    },
    {
      name: 'Dressings',
      ingredient_category: 'Condiments & Sauces',
      nutrient_type: 'Condiments & Sauces',
    },
    {
      name: 'Vinegars',
      ingredient_category: 'Condiments & Sauces',
      nutrient_type: 'Condiments & Sauces',
    },

    // Beverages
    { name: 'Coffee & Tea', ingredient_category: 'Beverages', nutrient_type: 'Beverages' },
    { name: 'Juice', ingredient_category: 'Beverages', nutrient_type: 'Beverages' },
    { name: 'Soft Drinks', ingredient_category: 'Beverages', nutrient_type: 'Beverages' },

    // Snacks & Prepared Foods
    {
      name: 'Snacks',
      ingredient_category: 'Snacks & Prepared Foods',
      nutrient_type: 'Snacks & Prepared Foods',
    },
    {
      name: 'Sweets & Desserts',
      ingredient_category: 'Snacks & Prepared Foods',
      nutrient_type: 'Snacks & Prepared Foods',
    },
    {
      name: 'Frozen Foods',
      ingredient_category: 'Snacks & Prepared Foods',
      nutrient_type: 'Snacks & Prepared Foods',
    },
    {
      name: 'Ready & Instant Meals',
      ingredient_category: 'Snacks & Prepared Foods',
      nutrient_type: 'Snacks & Prepared Foods',
    },
  ],
  units: [
    { name: 'piece', short_name: 'pc', type: 'count', to_base_factor: 1 },
    { name: 'gram', short_name: 'g', type: 'weight', to_base_factor: 1 },
    { name: 'kilogram', short_name: 'kg', type: 'weight', to_base_factor: 1000 },
    { name: 'ounce', short_name: 'oz', type: 'weight', to_base_factor: 28.3495 },
    { name: 'pound', short_name: 'lb', type: 'weight', to_base_factor: 453.592 },
    { name: 'milliliter', short_name: 'ml', type: 'volume', to_base_factor: 1 },
    { name: 'liter', short_name: 'l', type: 'volume', to_base_factor: 1000 },
    { name: 'cup', short_name: 'cup', type: 'volume', to_base_factor: 236.588 },
    { name: 'tablespoon', short_name: 'tbsp', type: 'volume', to_base_factor: 14.7868 },
    { name: 'teaspoon', short_name: 'tsp', type: 'volume', to_base_factor: 4.92892 },
    { name: 'clove', short_name: 'clv', type: 'count', to_base_factor: 1 },
    { name: 'pinch', short_name: 'pin', type: 'count', to_base_factor: 1 },
    { name: 'can', short_name: 'can', type: 'count', to_base_factor: 1 },
  ],
  difficulties: [
    { name: 'Easy' },
    { name: 'Medium' },
    { name: 'Hard' },
  ],
  ingredients: [
    // Fruits, vegetables, herbs & greens, and aromatics (Produce)
    { name: 'Apples', category: 'Fruits', default_unit: 'piece' },
    { name: 'Bananas', category: 'Fruits', default_unit: 'piece' },
    { name: 'Lemons', category: 'Fruits', default_unit: 'piece' },
    { name: 'Avocados', category: 'Fruits', default_unit: 'piece' },
    { name: 'Spinach', category: 'Vegetables', default_unit: 'gram' },
    { name: 'Onions', category: 'Vegetables', default_unit: 'piece' },
    { name: 'Carrots', category: 'Vegetables', default_unit: 'piece' },
    { name: 'Potatoes', category: 'Vegetables', default_unit: 'kilogram' },
    { name: 'Tomatoes', category: 'Vegetables', default_unit: 'piece' },
    { name: 'Garlic', category: 'Aromatics', default_unit: 'clove' },
    { name: 'Fresh Basil', category: 'Herbs & Greens', default_unit: 'gram' },

    // Meat, seafood, eggs, and legumes (Protein & Eggs)
    { name: 'Chicken Breast', category: 'Meat', default_unit: 'kilogram' },
    { name: 'Ground Beef', category: 'Meat', default_unit: 'kilogram' },
    { name: 'Pork Chops', category: 'Meat', default_unit: 'piece' },
    { name: 'Bacon', category: 'Meat', default_unit: 'gram' },
    { name: 'Salmon Fillet', category: 'Seafood', default_unit: 'kilogram' },
    { name: 'Canned Tuna', category: 'Seafood', default_unit: 'can' },
    { name: 'Large Eggs', category: 'Eggs', default_unit: 'piece' },
    { name: 'Chickpeas', category: 'Beans & Legumes', default_unit: 'can' },
    { name: 'Black Beans', category: 'Beans & Legumes', default_unit: 'can' },

    // Dairy
    { name: 'Milk', category: 'Milk & Cream', default_unit: 'liter' },
    { name: 'Heavy Cream', category: 'Milk & Cream', default_unit: 'milliliter' },
    { name: 'Cheddar Cheese', category: 'Cheese', default_unit: 'gram' },
    { name: 'Parmesan Cheese', category: 'Cheese', default_unit: 'gram' },
    { name: 'Feta Cheese', category: 'Cheese', default_unit: 'gram' },
    { name: 'Greek Yogurt', category: 'Yogurt & Cultured Dairy', default_unit: 'gram' },

    // Grains, pasta, bread, and baking ingredients (Grains & Bakery)
    { name: 'Basmati Rice', category: 'Grains', default_unit: 'kilogram' },
    { name: 'Quinoa', category: 'Grains', default_unit: 'gram' },
    { name: 'Rolled Oats', category: 'Grains', default_unit: 'gram' },
    { name: 'Spaghetti', category: 'Pasta', default_unit: 'gram' },
    { name: 'Penne Pasta', category: 'Pasta', default_unit: 'gram' },
    { name: 'Sourdough Bread', category: 'Bread & Bakery', default_unit: 'piece' },
    { name: 'All-Purpose Flour', category: 'Baking Ingredients', default_unit: 'kilogram' },
    { name: 'Granulated Sugar', category: 'Baking Ingredients', default_unit: 'kilogram' },
    { name: 'Brown Sugar', category: 'Baking Ingredients', default_unit: 'kilogram' },
    { name: 'Baking Powder', category: 'Baking Ingredients', default_unit: 'teaspoon' },
    { name: 'Honey', category: 'Baking Ingredients', default_unit: 'milliliter' },
    { name: 'Vanilla Extract', category: 'Baking Ingredients', default_unit: 'teaspoon' },

    // Oils, nuts, seeds, and nut butters (Oils, Nuts & Seeds)
    { name: 'Olive Oil', category: 'Oils', default_unit: 'milliliter' },
    { name: 'Vegetable Oil', category: 'Oils', default_unit: 'milliliter' },
    { name: 'Peanut Butter', category: 'Nut Butters', default_unit: 'gram' },
    { name: 'Almonds', category: 'Nuts & Seeds', default_unit: 'gram' },

    // Dairy butter
    { name: 'Unsalted Butter', category: 'Butter', default_unit: 'gram' },

    // Condiments & Sauces
    { name: 'Soy Sauce', category: 'Condiments', default_unit: 'milliliter' },
    { name: 'Ketchup', category: 'Condiments', default_unit: 'milliliter' },
    { name: 'Mayonnaise', category: 'Condiments', default_unit: 'milliliter' },
    { name: 'Dijon Mustard', category: 'Condiments', default_unit: 'teaspoon' },
    { name: 'Balsamic Vinegar', category: 'Vinegars', default_unit: 'milliliter' },
    { name: 'Marinara Sauce', category: 'Sauces', default_unit: 'milliliter' },
    { name: 'Diced Tomatoes', category: 'Sauces', default_unit: 'can' },
    { name: 'Coconut Milk', category: 'Sauces', default_unit: 'milliliter' },

    // Herbs, Spices & Seasonings
    { name: 'Salt', category: 'Seasoning Blends', default_unit: 'gram' },
    { name: 'Black Pepper', category: 'Spices & Dried Herbs', default_unit: 'gram' },
    { name: 'Cumin', category: 'Spices & Dried Herbs', default_unit: 'teaspoon' },
    { name: 'Paprika', category: 'Spices & Dried Herbs', default_unit: 'teaspoon' },
    { name: 'Dried Oregano', category: 'Spices & Dried Herbs', default_unit: 'teaspoon' },
    { name: 'Cinnamon', category: 'Spices & Dried Herbs', default_unit: 'teaspoon' },
    { name: 'Garlic Powder', category: 'Spices & Dried Herbs', default_unit: 'teaspoon' },

    // Snacks & Prepared Foods
    { name: 'Frozen Peas', category: 'Frozen Foods', default_unit: 'gram' },
    { name: 'Frozen Berries', category: 'Frozen Foods', default_unit: 'gram' },
    { name: 'Frozen Pizza', category: 'Frozen Foods', default_unit: 'piece' },
    { name: 'Vanilla Ice Cream', category: 'Sweets & Desserts', default_unit: 'liter' },
    { name: 'Potato Chips', category: 'Snacks', default_unit: 'gram' },
    { name: 'Pretzels', category: 'Snacks', default_unit: 'gram' },
    { name: 'Dark Chocolate', category: 'Sweets & Desserts', default_unit: 'gram' },

    // Beverages
    { name: 'Coffee Beans', category: 'Coffee & Tea', default_unit: 'kilogram' },
    { name: 'Earl Grey Tea', category: 'Coffee & Tea', default_unit: 'piece' },
    { name: 'Orange Juice', category: 'Juice', default_unit: 'liter' },
    { name: 'Cola', category: 'Soft Drinks', default_unit: 'can' },
  ],
  items: [
    // Fridge Items
    {
      ingredient: 'Milk',
      label: 'Horizon Whole Milk',
      quantity: 0.5,
      unit: 'liter',
      location: 'Fridge',
      expiration_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // Expired 2 days ago
      purchase_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      notes: 'Opened last week - spoiled',
    },
    {
      ingredient: 'Milk',
      label: 'Organic Valley Whole Milk',
      quantity: 2,
      unit: 'liter',
      location: 'Fridge',
      expiration_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000), // Fresh
      purchase_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      notes: 'Unopened 2L carton',
    },
    {
      ingredient: 'Large Eggs',
      label: 'Vital Farms Pasture-Raised Eggs',
      quantity: 12,
      unit: 'piece',
      location: 'Fridge',
      expiration_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      notes: 'Grade A large brown eggs',
    },
    {
      ingredient: 'Cheddar Cheese',
      label: 'Tillamook Sharp Cheddar Block',
      quantity: 250,
      unit: 'gram',
      location: 'Fridge',
      purchase_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      expiration_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      notes: 'Aged sharp white cheddar',
    },
    {
      ingredient: 'Spinach',
      label: 'Organic Baby Spinach Tub',
      quantity: 300,
      unit: 'gram',
      location: 'Fridge',
      expiration_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // Expiring tomorrow!
      purchase_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      notes: 'Use soon for salads or sautéing',
    },
    {
      ingredient: 'Greek Yogurt',
      label: 'Chobani Plain 0% Greek Yogurt',
      quantity: 500,
      unit: 'gram',
      location: 'Fridge',
      expiration_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      notes: 'Family size tub',
    },
    {
      ingredient: 'Unsalted Butter',
      label: 'Kerrygold Pure Irish Unsalted Butter',
      quantity: 200,
      unit: 'gram',
      location: 'Fridge',
      expiration_date: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      notes: '82% butterfat blocks',
    },
    {
      ingredient: 'Mayonnaise',
      label: 'Hellmann’s Real Mayonnaise',
      quantity: 400,
      unit: 'milliliter',
      location: 'Fridge',
      expiration_date: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
      opened_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      notes: 'Opened, stored in fridge door',
    },
    {
      ingredient: 'Dijon Mustard',
      label: 'Grey Poupon Dijon Mustard Jar',
      quantity: 200,
      unit: 'gram',
      location: 'Fridge',
      expiration_date: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
      notes: 'Smooth Dijon mustard',
    },

    // Pantry Items
    {
      ingredient: 'All-Purpose Flour',
      label: 'King Arthur Unbleached Flour',
      quantity: 1.5,
      unit: 'kilogram',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
      notes: 'Non-GMO all-purpose baking flour bag',
    },
    {
      ingredient: 'Granulated Sugar',
      label: 'Domino Pure Cane Sugar',
      quantity: 1,
      unit: 'kilogram',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    },
    {
      ingredient: 'Spaghetti',
      label: 'Barilla Bronze Cut Spaghetti #5',
      quantity: 500,
      unit: 'gram',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
      notes: 'Semolina pasta box',
    },
    {
      ingredient: 'Basmati Rice',
      label: 'Royal Chef Extra Long Basmati Rice',
      quantity: 5,
      unit: 'kilogram',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
      notes: 'Large burlap sack from Costco',
    },
    {
      ingredient: 'Chickpeas',
      label: 'Goya Organic Chickpeas',
      quantity: 3,
      unit: 'can',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    },
    {
      ingredient: 'Diced Tomatoes',
      label: 'Muir Glen Fire Roasted Diced Tomatoes',
      quantity: 4,
      unit: 'can',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    },
    {
      ingredient: 'Olive Oil',
      label: 'California Olive Ranch EVOO',
      quantity: 750,
      unit: 'milliliter',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
      notes: '100% California Extra Virgin Olive Oil',
    },
    {
      ingredient: 'Salt',
      label: 'Morton Coarse Kosher Salt Box',
      quantity: 300,
      unit: 'gram',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 730 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    },
    {
      ingredient: 'Black Pepper',
      label: 'McCormick Whole Black Peppercorns Grinder',
      quantity: 50,
      unit: 'gram',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
      notes: 'Glass spice grinder bottle',
    },
    {
      ingredient: 'Honey',
      label: 'Nate’s 100% Pure Raw & Unfiltered Honey',
      quantity: 250,
      unit: 'milliliter',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 730 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
      notes: 'Squeeze bottle',
    },
    {
      ingredient: 'Peanut Butter',
      label: 'Jif Creamy Peanut Butter Jar',
      quantity: 500,
      unit: 'gram',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    },

    // Shelf / Produce Pantry Items
    {
      ingredient: 'Apples',
      label: 'Honeycrisp Apples Bag',
      quantity: 6,
      unit: 'piece',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    },
    {
      ingredient: 'Bananas',
      label: 'Organic Yellow Bananas Bunch',
      quantity: 4,
      unit: 'piece',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      notes: 'Getting ripe, good for banana bread soon',
    },
    {
      ingredient: 'Onions',
      label: 'Yellow Sweet Onions Mesh Bag',
      quantity: 5,
      unit: 'piece',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    },
    {
      ingredient: 'Potatoes',
      label: 'Yukon Gold Potatoes Bag',
      quantity: 2,
      unit: 'kilogram',
      location: 'Pantry',
      expiration_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    },

    // Freezer Items
    {
      ingredient: 'Frozen Peas',
      label: 'Birds Eye Sweet Garden Peas',
      quantity: 500,
      unit: 'gram',
      location: 'Freezer',
      expiration_date: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    },
    {
      ingredient: 'Frozen Pizza',
      label: 'DiGiorno Rising Crust Pepperoni Pizza',
      quantity: 2,
      unit: 'piece',
      location: 'Freezer',
      expiration_date: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
      notes: 'Emergency quick dinner',
    },
    {
      ingredient: 'Chicken Breast',
      label: 'Kirkland Organic Chicken Breasts',
      quantity: 1,
      unit: 'kilogram',
      location: 'Freezer',
      expiration_date: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      notes: 'Freezer sealed vacuum pack',
    },
    {
      ingredient: 'Vanilla Ice Cream',
      label: 'Häagen-Dazs Vanilla Bean Ice Cream',
      quantity: 1,
      unit: 'liter',
      location: 'Freezer',
      expiration_date: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
      purchase_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      notes: 'Family tub',
    },
  ],
  recipes: [
    {
      name: 'Fresh Fruit Salad',
      description: 'A refreshing salad made with fresh apples, bananas, and a drizzle of honey.',
      difficulty: 'Easy',
      servings: 2,
      prep_time: 5,
      cook_time: 0,
      ingredients: [
        { ingredient: 'Apples', quantity: 2, unit: 'piece' },
        { ingredient: 'Bananas', quantity: 2, unit: 'piece' },
        { ingredient: 'Honey', quantity: 1, unit: 'tablespoon' },
      ],
      steps: [
        { step_number: 1, instruction_text: 'Dice apples and slice bananas into a bowl.' },
        { step_number: 2, instruction_text: 'Drizzle with honey and toss gently to serve.' },
      ],
    },
    {
      name: 'Simple Egg Fried Rice',
      description: 'A quick 10-minute fried rice made with basic pantry staples.',
      difficulty: 'Easy',
      servings: 2,
      prep_time: 5,
      cook_time: 10,
      ingredients: [
        { ingredient: 'Basmati Rice', quantity: 200, unit: 'gram' },
        { ingredient: 'Large Eggs', quantity: 2, unit: 'piece' },
        { ingredient: 'Olive Oil', quantity: 1, unit: 'tablespoon' },
        { ingredient: 'Salt', quantity: 1, unit: 'gram' },
      ],
      steps: [
        { step_number: 1, instruction_text: 'Heat olive oil in a skillet over medium-high heat.' },
        {
          step_number: 2,
          instruction_text: 'Scramble the eggs until just cooked, then add cooked rice and salt.',
        },
        { step_number: 3, instruction_text: 'Stir fry for 3-5 minutes until steaming hot.' },
      ],
    },
    {
      name: 'Classic Pancakes',
      description: 'Fluffy and golden pancakes, perfect for a weekend breakfast.',
      difficulty: 'Easy',
      servings: 4,
      prep_time: 10,
      cook_time: 15,
      ingredients: [
        { ingredient: 'All-Purpose Flour', quantity: 250, unit: 'gram' },
        { ingredient: 'Granulated Sugar', quantity: 2, unit: 'tablespoon' },
        { ingredient: 'Baking Powder', quantity: 2, unit: 'teaspoon' },
        { ingredient: 'Salt', quantity: 0.5, unit: 'teaspoon' },
        { ingredient: 'Milk', quantity: 300, unit: 'milliliter' },
        { ingredient: 'Large Eggs', quantity: 1, unit: 'piece' },
        { ingredient: 'Unsalted Butter', quantity: 45, unit: 'gram' },
        { ingredient: 'Vanilla Extract', quantity: 1, unit: 'teaspoon' },
      ],
      steps: [
        {
          step_number: 1,
          instruction_text:
            'In a large bowl, whisk together flour, sugar, baking powder, and salt.',
        },
        {
          step_number: 2,
          instruction_text:
            'In a separate bowl, whisk together milk, egg, melted butter, and vanilla.',
        },
        {
          step_number: 3,
          instruction_text:
            'Pour the wet ingredients into the dry ingredients and stir until just combined. Lumps are okay!',
        },
        {
          step_number: 4,
          instruction_text: 'Heat a non-stick pan or griddle over medium heat. Grease lightly.',
        },
        {
          step_number: 5,
          instruction_text:
            'Pour 1/4 cup of batter for each pancake. Cook until bubbles form on the surface, then flip and cook until golden brown.',
          timer_seconds: 180, // 3 mins
        },
      ],
    },
    {
      name: 'Spaghetti with Marinara',
      description: 'A quick and easy weeknight pasta dish.',
      difficulty: 'Easy',
      servings: 2,
      prep_time: 5,
      cook_time: 15,
      ingredients: [
        { ingredient: 'Spaghetti', quantity: 200, unit: 'gram' },
        { ingredient: 'Marinara Sauce', quantity: 300, unit: 'milliliter' },
        { ingredient: 'Olive Oil', quantity: 1, unit: 'tablespoon' },
        { ingredient: 'Parmesan Cheese', quantity: 20, unit: 'gram' },
      ],
      steps: [
        {
          step_number: 1,
          instruction_text: 'Bring a large pot of salted water to a boil.',
        },
        {
          step_number: 2,
          instruction_text: 'Add spaghetti and cook until al dente.',
          timer_seconds: 600, // 10 mins
        },
        {
          step_number: 3,
          instruction_text:
            'While pasta cooks, heat the marinara sauce in a saucepan over medium heat.',
        },
        {
          step_number: 4,
          instruction_text: 'Drain the pasta and toss with the warm sauce.',
        },
        {
          step_number: 5,
          instruction_text: 'Serve topped with grated Parmesan cheese and a drizzle of olive oil.',
        },
      ],
    },
    {
      name: 'Greek Salad',
      description: 'Fresh and healthy salad with Mediterranean flavors.',
      difficulty: 'Easy',
      servings: 2,
      prep_time: 15,
      cook_time: 0,
      ingredients: [
        { ingredient: 'Tomatoes', quantity: 3, unit: 'piece' },
        { ingredient: 'Avocados', quantity: 1, unit: 'piece' }, // Creative twist
        { ingredient: 'Onions', quantity: 0.5, unit: 'piece' },
        { ingredient: 'Feta Cheese', quantity: 100, unit: 'gram' },
        { ingredient: 'Olive Oil', quantity: 2, unit: 'tablespoon' },
        { ingredient: 'Dried Oregano', quantity: 1, unit: 'teaspoon' },
      ],
      steps: [
        {
          step_number: 1,
          instruction_text: 'Chop tomatoes and avocado into bite-sized chunks.',
        },
        {
          step_number: 2,
          instruction_text: 'Slice the onion thinly.',
        },
        {
          step_number: 3,
          instruction_text: 'Combine vegetables in a bowl.',
        },
        {
          step_number: 4,
          instruction_text:
            'Top with crumbled feta cheese, drizzle with olive oil, and sprinkle with oregano.',
        },
      ],
    },
    {
      name: 'Chicken Curry',
      description: 'Flavorful chicken curry with coconut milk.',
      difficulty: 'Medium',
      servings: 4,
      prep_time: 20,
      cook_time: 30,
      ingredients: [
        { ingredient: 'Chicken Breast', quantity: 500, unit: 'gram' },
        { ingredient: 'Onions', quantity: 1, unit: 'piece' },
        { ingredient: 'Garlic', quantity: 3, unit: 'clove' },
        { ingredient: 'Coconut Milk', quantity: 400, unit: 'milliliter' },
        { ingredient: 'Vegetable Oil', quantity: 1, unit: 'tablespoon' },
        { ingredient: 'Cumin', quantity: 1, unit: 'teaspoon' },
        { ingredient: 'Paprika', quantity: 1, unit: 'teaspoon' },
        { ingredient: 'Basmati Rice', quantity: 300, unit: 'gram' },
      ],
      steps: [
        {
          step_number: 1,
          instruction_text: 'Dice the chicken into cubes. Chop onion and mince garlic.',
        },
        {
          step_number: 2,
          instruction_text: 'Heat oil in a pan. Sauté onions and garlic until soft.',
        },
        {
          step_number: 3,
          instruction_text:
            'Add chicken and spices (cumin, paprika) and cook until chicken is browned.',
        },
        {
          step_number: 4,
          instruction_text:
            'Pour in coconut milk and simmer for 15-20 minutes until chicken is cooked through and sauce thickens.',
          timer_seconds: 900, // 15 mins
        },
        {
          step_number: 5,
          instruction_text: 'Serve hot over steamed basmati rice.',
        },
      ],
    },
    {
      name: 'Banana Bread',
      description: 'Moist and delicious way to use up overripe bananas.',
      difficulty: 'Medium',
      servings: 8,
      prep_time: 15,
      cook_time: 60,
      ingredients: [
        { ingredient: 'Bananas', quantity: 3, unit: 'piece' },
        { ingredient: 'All-Purpose Flour', quantity: 250, unit: 'gram' },
        { ingredient: 'Granulated Sugar', quantity: 150, unit: 'gram' },
        { ingredient: 'Unsalted Butter', quantity: 75, unit: 'gram' },
        { ingredient: 'Large Eggs', quantity: 1, unit: 'piece' },
        { ingredient: 'Baking Powder', quantity: 1, unit: 'teaspoon' },
        { ingredient: 'Cinnamon', quantity: 1, unit: 'teaspoon' },
        { ingredient: 'Vanilla Extract', quantity: 1, unit: 'teaspoon' },
      ],
      steps: [
        {
          step_number: 1,
          instruction_text: 'Preheat oven to 350°F (175°C). Grease a loaf pan.',
        },
        {
          step_number: 2,
          instruction_text: 'Mash the ripe bananas in a bowl.',
        },
        {
          step_number: 3,
          instruction_text: 'Mix in melted butter, then sugar, egg, and vanilla.',
        },
        {
          step_number: 4,
          instruction_text: 'Sprinkle baking powder and cinnamon over the banana mixture.',
        },
        {
          step_number: 5,
          instruction_text: 'Gently stir in the flour until just incorporated.',
        },
        {
          step_number: 6,
          instruction_text: 'Pour batter into the loaf pan and bake for 60 minutes.',
          timer_seconds: 3600, // 60 mins
        },
      ],
    },
  ],
  meal_plans: [
    {
      day: 'Monday',
      meal_type: 'Breakfast',
      recipe_name: 'Classic Pancakes',
      prep_time_minutes: 25,
      calories: 480,
      servings: 4,
      cooked: 1,
      missing_ingredients: [],
      tags: ['Easy', 'Breakfast'],
    },
    {
      day: 'Monday',
      meal_type: 'Dinner',
      recipe_name: 'Spaghetti with Marinara',
      prep_time_minutes: 20,
      calories: 520,
      servings: 2,
      cooked: 0,
      missing_ingredients: ['Spaghetti', 'Marinara Sauce', 'Parmesan Cheese'],
      tags: ['Italian', 'Pasta'],
    },
    {
      day: 'Tuesday',
      meal_type: 'Lunch',
      recipe_name: 'Greek Salad',
      prep_time_minutes: 15,
      calories: 340,
      servings: 2,
      cooked: 0,
      missing_ingredients: ['Feta Cheese', 'Avocados'],
      tags: ['Healthy', 'Vegetarian'],
    },
    {
      day: 'Wednesday',
      meal_type: 'Lunch',
      recipe_name: 'Simple Egg Fried Rice',
      prep_time_minutes: 15,
      calories: 420,
      servings: 2,
      cooked: 1,
      missing_ingredients: [],
      tags: ['Quick', 'Asian'],
    },
    {
      day: 'Thursday',
      meal_type: 'Dinner',
      recipe_name: 'Chicken Curry',
      prep_time_minutes: 50,
      calories: 650,
      servings: 4,
      cooked: 0,
      missing_ingredients: ['Chicken Breast', 'Coconut Milk'],
      tags: ['High Protein', 'Curry'],
    },
    {
      day: 'Friday',
      meal_type: 'Snacks',
      recipe_name: 'Fresh Fruit Salad',
      prep_time_minutes: 5,
      calories: 180,
      servings: 2,
      cooked: 0,
      missing_ingredients: [],
      tags: ['Fresh', 'Fruit'],
    },
    {
      day: 'Saturday',
      meal_type: 'Snacks',
      recipe_name: 'Banana Bread',
      prep_time_minutes: 75,
      calories: 310,
      servings: 8,
      cooked: 0,
      missing_ingredients: ['Cinnamon', 'Vanilla Extract'],
      tags: ['Baking', 'Dessert'],
    },
  ],
  users: [
    {
      id: 'usr_00000000-0000-4000-8000-000000000001',
      email: 'chef@pantry.app',
      fullName: 'Head Chef',
      globalRole: 'admin',
      password: 'password123',
      themePreference: 'system',
      locale: 'en',
    },
  ],
  kitchens: [
    {
      id: 'ktc_00000000-0000-4000-8000-000000000000',
      name: 'Main Kitchen',
      description: 'Default shared workspace for existing pantry inventory',
    },
  ],
  stores: [
    { name: "Trader Joe's" },
    { name: 'Safeway' },
    { name: 'Whole Foods' },
    { name: 'Costco' },
  ],
  shopping_list_items: [
    {
      name: 'Olive Oil (Extra Virgin)',
      ingredient: 'Olive Oil',
      category: 'Pantry',
      quantity: 1,
      unit: 'bottle',
      checked: 0,
      estimated_price: 9.99,
      store_name: "Trader Joe's",
      source: 'low_stock',
    },
    {
      name: 'Heavy Cream',
      ingredient: 'Heavy Cream',
      category: 'Dairy',
      quantity: 1,
      unit: 'carton',
      checked: 1,
      estimated_price: 3.49,
      store_name: 'Safeway',
      source: 'recipe_plan',
      recipe_name: 'Spaghetti with Marinara',
    },
    {
      name: 'Fresh Basil',
      ingredient: 'Fresh Basil',
      category: 'Produce',
      quantity: 1,
      unit: 'bunch',
      checked: 0,
      estimated_price: 2.50,
      store_name: 'Whole Foods',
      source: 'recipe_plan',
      recipe_name: 'Spaghetti with Marinara',
    },
    {
      name: 'Garlic Bulbs',
      ingredient: 'Garlic',
      category: 'Produce',
      quantity: 2,
      unit: 'heads',
      checked: 0,
      estimated_price: 1.20,
      store_name: "Trader Joe's",
      source: 'low_stock',
    },
    {
      name: 'Salmon Fillets',
      ingredient: 'Salmon Fillet',
      category: 'Seafood',
      quantity: 2,
      unit: 'pcs',
      checked: 0,
      estimated_price: 14.50,
      store_name: 'Costco',
      source: 'recipe_plan',
      recipe_name: 'Chicken Curry',
    },
    {
      name: 'Parmesan Cheese',
      ingredient: 'Parmesan Cheese',
      category: 'Dairy',
      quantity: 1,
      unit: 'wedge',
      checked: 0,
      estimated_price: 5.99,
      store_name: 'Whole Foods',
      source: 'recipe_plan',
      recipe_name: 'Spaghetti with Marinara',
    },
  ],
};
